package daro.lang.parser;

import daro.lang.ast.Position;
import daro.lang.interpreter.DaroException;

/**
 * This class is used to hold errors generated by the {@link Parser} during the
 * parsing process.
 *
 * @author Roland Bernard
 */
public class ParsingException extends DaroException {
    private static final long serialVersionUID = 1L;

    /**
     * Creates a new parser error for the given position and with the given message.
     * 
     * @param position The position of the error
     * @param message  The message of the message
     */
    public ParsingException(Position position, String message) {
        super(position, message);
    }

    @Override
    public String toString() {
        return "Syntax error at " + getPosition() + ": " + getMessage();
    }
}
